users=[{'eid':1,'ename':'Alonso','gender':'Male'},
{'eid':2,'ename':'Aigneis','gender':'Female'},
{'eid':3,'ename':'Elvyn','gender':'Male'},
{'eid':4,'ename':'Reagen','gender':'Male'},
{'eid':5,'ename':'Izzy','gender':'Male'},
{'eid':6,'ename':'Zollie','gender':'Male'},
{'eid':7,'ename':'Peta','gender':'Female'},
{'eid':8,'ename':'Ambrosi','gender':'Male'},
{'eid':9,'ename':'Kalle','gender':'Male'},
{'eid':10,'ename':'Wyatan','gender':'Non-binary'},
{'eid':11,'ename':'Esmaria','gender':'Female'},
{'eid':12,'ename':'Evie','gender':'Female'},
{'eid':13,'ename':'Berkeley','gender':'Male'},
{'eid':14,'ename':'Phillida','gender':'Female'},
{'eid':15,'ename':'Adrianne','gender':'Female'},
{'eid':16,'ename':'Heindrick','gender':'Male'},
{'eid':17,'ename':'Dugald','gender':'Male'},
{'eid':18,'ename':'Lamar','gender':'Male'},
{'eid':19,'ename':'Dodie','gender':'Non-binary'},
{'eid':20,'ename':'Rabbi','gender':'Male'},
{'eid':21,'ename':'Rob','gender':'Male'},
{'eid':22,'ename':'Amabelle','gender':'Genderfluid'},
{'eid':23,'ename':'Enid','gender':'Female'},
{'eid':24,'ename':'Hersch','gender':'Male'},
{'eid':25,'ename':'Enid','gender':'Polygender'},
{'eid':26,'ename':'Ennis','gender':'Male'},
{'eid':27,'ename':'Annalee','gender':'Female'},
{'eid':28,'ename':'Asia','gender':'Female'},
{'eid':29,'ename':'Hewitt','gender':'Male'},
{'eid':30,'ename':'Bernadette','gender':'Female'},
{'eid':31,'ename':'Ricki','gender':'Female'},
{'eid':32,'ename':'Costanza','gender':'Female'},
{'eid':33,'ename':'Maisey','gender':'Female'},
{'eid':34,'ename':'Bethany','gender':'Female'},
{'eid':35,'ename':'Selby','gender':'Male'},
{'eid':36,'ename':'Tiffany','gender':'Female'},
{'eid':37,'ename':'Gerhard','gender':'Male'},
{'eid':38,'ename':'Nikolaus','gender':'Male'},
{'eid':39,'ename':'Darla','gender':'Female'},
{'eid':40,'ename':'Lenee','gender':'Female'},
{'eid':41,'ename':'Gerome','gender':'Male'},
{'eid':42,'ename':'Benjy','gender':'Male'},
{'eid':43,'ename':'Adolf','gender':'Male'},
{'eid':44,'ename':'Otto','gender':'Male'},
{'eid':45,'ename':'Germaine','gender':'Male'},
{'eid':46,'ename':'Maynard','gender':'Male'},
{'eid':47,'ename':'Marlena','gender':'Female'},
{'eid':48,'ename':'Beulah','gender':'Female'},
{'eid':49,'ename':'Adrianne','gender':'Female'},
{'eid':50,'ename':'Natale','gender':'Male'},
{'eid':51,'ename':'Raffaello','gender':'Male'},
{'eid':52,'ename':'Katha','gender':'Female'},
{'eid':53,'ename':'Grant','gender':'Male'},
{'eid':54,'ename':'Danyette','gender':'Female'},
{'eid':55,'ename':'Ody','gender':'Male'},
{'eid':56,'ename':'Zita','gender':'Female'},
{'eid':57,'ename':'Samaria','gender':'Female'},
{'eid':58,'ename':'Dniren','gender':'Female'},
{'eid':59,'ename':'Andria','gender':'Female'},
{'eid':60,'ename':'Melisandra','gender':'Female'},
{'eid':61,'ename':'Sherie','gender':'Female'},
{'eid':62,'ename':'Rana','gender':'Female'},
{'eid':63,'ename':'Karisa','gender':'Female'},
{'eid':64,'ename':'Charo','gender':'Female'},
{'eid':65,'ename':'Celie','gender':'Female'},
{'eid':66,'ename':'Kylen','gender':'Female'},
{'eid':67,'ename':'Trevor','gender':'Male'},
{'eid':68,'ename':'Willetta','gender':'Female'},
{'eid':69,'ename':'Linea','gender':'Female'},
{'eid':70,'ename':'Ainslie','gender':'Bigender'},
{'eid':71,'ename':'Wendell','gender':'Male'},
{'eid':72,'ename':'Micheal','gender':'Male'},
{'eid':73,'ename':'Delcine','gender':'Female'},
{'eid':74,'ename':'Feliza','gender':'Female'},
{'eid':75,'ename':'Chevalier','gender':'Male'},
{'eid':76,'ename':'Les','gender':'Male'},
{'eid':77,'ename':'Philipa','gender':'Female'},
{'eid':78,'ename':'Mozelle','gender':'Female'},
{'eid':79,'ename':'Evonne','gender':'Female'},
{'eid':80,'ename':'Cedric','gender':'Male'},
{'eid':81,'ename':'Henriette','gender':'Female'},
{'eid':82,'ename':'Vaclav','gender':'Male'},
{'eid':83,'ename':'Dionisio','gender':'Male'},
{'eid':84,'ename':'Horatia','gender':'Female'},
{'eid':85,'ename':'Neda','gender':'Bigender'},
{'eid':86,'ename':'Langsdon','gender':'Male'},
{'eid':87,'ename':'Brnaba','gender':'Male'},
{'eid':88,'ename':'Sandro','gender':'Male'},
{'eid':89,'ename':'Ronna','gender':'Female'},
{'eid':90,'ename':'Artair','gender':'Male'},
{'eid':91,'ename':'Mayne','gender':'Male'},
{'eid':92,'ename':'Cob','gender':'Male'},
{'eid':93,'ename':'Wynn','gender':'Male'},
{'eid':94,'ename':'Huntington','gender':'Male'},
{'eid':95,'ename':'Jeanna','gender':'Female'},
{'eid':96,'ename':'Dennis','gender':'Male'},
{'eid':97,'ename':'Frederica','gender':'Female'},
{'eid':98,'ename':'Nettle','gender':'Agender'},
{'eid':99,'ename':'Ikey','gender':'Male'},
{'eid':100,'ename':'Forester','gender':'Male'}]

""" 

print(len(users))
print(type(users)) """

no_male_users=0
for user in users:
    if user['gender'] =='Male':
        no_male_users = no_male_users+1


print("Total users:",len(users))
print("No of Male Users:",no_male_users)